version: '3'

networks: 
    rede_1:

services: 

    central:
        image: ainv_central:v1_00
        working_dir: /app
        ports: 
            - 9001:8080
        networks: 
            - rede_1
        depends_on:
          - database

    database:
        image: mysql:5.7
        ports: 
            - "7001:3306"
        environment:
            MYSQL_DATABASE: invest_master_dev
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - H:\Docker\MySql\volumes:/var/lib/mysql
        networks:
          - rede_1