INSERT INTO ativo (nome, codigo)
VALUES 
('3M BDR','MMMC34'),
('Abbott Laboratories BDR','ABTT34'),
('Abbvie BDR','ABBV34'),
('ABC Brasil PN','ABCB4'),
('Accenture BDR','ACNB34'),
('Advance Auto','A1AP34'),
('Advanced-Dh ON','ADHM3'),
('Aes Tiete Energia Pref Rights','TIET2'),
('AES Tiete ON','TIET3'),
('AES Tiete PN','TIET4'),
('AES Tiete Unit ','TIET11'),
('Afluente Transmissao de Energia','AFLT3'),
('AIG BDR','AIGB34'),
('Air Products','A1PD34'),
('Akamai Tech','A1KA34'),
('Alaska Air','A1LK34'),
('Alfa Administracao Pref','BRGE6'),
('Alfa Administracao Pref E','BRGE11'),
('Alfa Administracao Pref F','BRGE12'),
('Alfa De Admin','BRGE3'),
('Alfa De Admin A Pref','BRGE5'),
('Alfa De Admin D Pref','BRGE8'),
('Alfa Holdings ON','RPAD3'),
('Alfa Holdings PNA','RPAD5'),
('Alfa Holdings PNB','RPAD6'),
('Alianca Bahia','PEAB3'),
('Alianca da Bahia PN','PEAB4'),
('Aliansce Sonae','ALSO3'),
('Align Tech','A1LG34'),
('Alliance Data','A1LL34'),
('Alliar ON','AALR3'),
('Alpargatas ON','ALPA3'),
('Alpargatas PN','ALPA4'),
('Alphabet A BDR','GOGL34'),
('Alphabet C BDR','GOGL35'),
('Alupar Invest ON','ALUP3'),
('Alupar Invest PN','ALUP4'),
('Alupar Invest Unit','ALUP11'),
('Amazon.com BDR','AMZO34'),
('Amazonia ON','BAZA3'),
('Ambev ON','ABEV3'),
('American Airlines BDR','AALL34'),
('American Express BDR','AXPB34'),
('Amgen BDR','AMGN34'),
('Ampla ON','CBEE3'),
('Anima ON','ANIM3'),
('Anthem','A1NT34'),
('Apple BDR','AAPL34'),
('Arcelor Mittal BDR','ARMT34'),
('Arconic BDR','ARNC34'),
('Arezzo ON','ARZZ3'),
('Atompar ON','ATOM3'),
('ATT BDR','ATTB34'),
('Avon Products BDR','AVON34'),
('Azevedo & Travassos PN','AZEV4'),
('Azevedo Travassos','AZEV3'),
('Azul PN','AZUL4'),
('B2W Digital ON','BTOW3'),
('B3 ON','B3SA3'),
('Bahema','BAHI3'),
('Banco ABC Brasil','ABCB10'),
('Banco Alfa ON','BRIV3'),
('Banco Alfa PN','BRIV4'),
('Banco BMG PN','BMGB4'),
('Banco BTG Pactual','BPAC3'),
('Banco BTG Pactual Pref','BPAC5'),
('Banco do Brasil ON','BBAS3'),
('Banco do Estado de Sergipe','BGIP3'),
('Banco Indusval','IDVL9'),
('Banco Inter ON','BIDI3'),
('Banco Inter PN','BIDI4'),
('Banco Inter PN Termo','BIDI4T'),
('Banco Inter Unit','BIDI11'),
('Banco Mercantil de Investimentos ON','BMIN3'),
('Banco Mercantil do Brasil ON','BMEB3'),
('Banco Mercantil do Brasil PN','BMEB4'),
('Banco Mercantil PN','BMIN4'),
('Banco Pan PN','BPAN4'),
('Banese PN','BGIP4'),
('Banestes ON','BEES3'),
('Banestes PN','BEES4'),
('Bank of America BDR','BOAC34'),
('Bank of New York Mellon BDR','BONY34'),
('Banrisul ON','BRSR3'),
('Banrisul PNA','BRSR5'),
('Banrisul PNB','BRSR6'),
('Bardella PN','BDLL4'),
('Barigui Rendimento Imobiliários I','BARI11'),
('Battistella','BTTL3'),
('Baumer','BALM3'),
('Baumer PN','BALM4'),
('BB Recebiveis Imobiliários','BBIM11'),
('BB Renda de Papeis Imobiliários II','RDPD11'),
('BB Seguridade ON','BBSE3'),
('Berkshire Hathaway BDR','BERK34'),
('Best Buy BDR','BBYY34'),
('Bicicletas Monark ON','BMKS3'),
('Biogen BDR','BIIB34'),
('Biomarin','B1MR34'),
('Biomm ON','BIOM3'),
('Biosev ON','BSEV3'),
('Biotoscana BDR','GBIO33'),
('Blackrock BDR','BLAK34'),
('Bluemacaw Office','BLMO11'),
('BNB ON','BNBR3'),
('Boeing BDR','BOEI34'),
('Bombril PN','BOBR4'),
('Boston Properties BDR','BOXP34'),
('BR Brokers ON','BBRK3'),
('BR Insurance Corretora ON','APER3'),
('BR Malls Par ON','BRML3'),
('BR Pharma ON','BPHA3'),
('BR Propert ON','BRPR3'),
('Bradesco ON','BBDC3'),
('Bradesco PN ','BBDC4'),
('Bradespar ON','BRAP3'),
('Bradespar PN','BRAP4'),
('Bras Eletrobr A Pref','ELET5'),
('Brasil Varejo','BVAR11'),
('Brasilagro ON','AGRO3'),
('Brasilio Machado','BMII11'),
('Braskem ON','BRKM3'),
('Braskem PN','BRKM5'),
('Braskem Pref B','BRKM6'),
('Brazil Realty','BZLI11'),
('Brb Banco','BSLI3'),
('BRB PN','BSLI4'),
('Bresco Logistica','BRCO11'),
('BRF ON','BRFS3'),
('Brinquedos Estrela PN','ESTR4'),
('Bristol Myers Squibb BDR','BMYB34'),
('Brz Infra Portos','BRZP11'),
('Btg Pact Shp','BPML11'),
('Btg Pactual','BTLG11'),
('BTG Pactual Unit','BPAC11'),
('Burger King ON','BKBR3'),
('C&A Modas ON','CEAB3'),
('Cambuci Pref','CAMB10'),
('Cambuci SA','CAMB3'),
('Camil ON','CAML3'),
('Capitania','CPFF11'),
('Carrefour ON','CRFB3'),
('Caterpillar BDR','CATP34'),
('Cboe Global','C1BO34'),
('CCR ON','CCRO3'),
('CCX Carvao ON','CCXC3'),
('CEB ON','CEBR3'),
('Cedro Cachoeira ON','CEDO3'),
('Cedro PN','CEDO4'),
('CEEE-D ON','CEED3'),
('CEEE-GT ON','EEEL3'),
('Celesc PN','CLSC4'),
('Celgene BDR','CLGN34'),
('Celgpar ON','GPAR3'),
('Celpa PN','EQPA5'),
('Celpe PN','CEPE5'),
('Celulose Irani ON','RANI3'),
('Celulose Irani PN','RANI4'),
('Cemepe Investimentos ON','MAPT3'),
('Cemepe Pref ','MAPT4'),
('Cemig ON','CMIG3'),
('Cemig PN','CMIG4'),
('Cesp ON','CESP3'),
('Cesp PNA','CESP5'),
('Cesp PNB','CESP6'),
('Ch Robinson','C1HR34'),
('Charles Schwab BDR','SCHW34'),
('Chesapeake Energy BDR','CHKE34'),
('Chevron BDR','CHVX34'),
('Cia Hering ON','HGTX3'),
('Cielo ON','CIEL3'),
('Cigna','C1IC34'),
('Cisco Systems BDR','CSCO34'),
('Citigroup BDR','CTGP34'),
('Coca Cola BDR','COCA34'),
('Coelba ON','CEEB3'),
('Coelba PN','CEEB5'),
('Coelce ON','COCE3'),
('Coelce PNA','COCE5'),
('Cogna Educacao','COGN3'),
('Cognizant Tech BDR','CTSH34'),
('Colgate Palmolive BDR','COLG34'),
('Comcast BDR','CMCS34'),
('Comgas ON','CGAS3'),
('Comgas PNA','CGAS5'),
('Companhia Melhoramentos ON','MSPA3'),
('Con Ad Lin Pref','CALI4'),
('ConocoPhillips BDR','COPH34'),
('Copasa ON','CSMG3'),
('Copel ON','CPLE3'),
('Copel PNB','CPLE6'),
('Correa Ribeiro','CORR4'),
('Cosan Log ON','RLOG3'),
('Cosan ON','CSAN3'),
('Cosern ON','CSRN3'),
('Costco Wholesale BDR','COWC34'),
('Coteminas ON','CTNM3'),
('Coteminas PN','CTNM4'),
('Coty BDR','COTY34'),
('CPFL Energia ON','CPFE3'),
('CPFL Renovav ON','CPRE3'),
('CPFL Renovaveis','CPRE3T'),
('CR2 ON','CRDE3'),
('Cristal Pigmentos','CRPG3'),
('Cristal Pigmentos PNA','CRPG5'),
('Cristal Pigmentos PNB','CRPG6'),
('CSHG Imobiliário FOF','HGFF11'),
('CSN ON','CSNA3'),
('CSU Cardsyst ON','CARD3'),
('CTEEP ON','TRPL3'),
('CTEEP PN','TRPL4'),
('CVC Brasil ON','CVCB3'),
('CVC Viagens ON Termo','CVCB3T'),
('CVS Health BDR','CVSH34'),
('Cyre CCP ON','CCPR3'),
('Cyrela Realt ON','CYRE3'),
('Danaherrp BDR','DHER34'),
('Dasa ON','DASA3'),
('De Santa Catar','CLSC3'),
('Delta Air Lines BDR','DEAI34'),
('Diamondback','F1AN34'),
('Digital Realty','D1LR34'),
('Dimed ON','PNVL3'),
('Dimed PN','PNVL4'),
('Direcional ON','DIRR3'),
('Discover Fin','D1FS34'),
('Dohler PN','DOHL4'),
('Dommo Energia','DMMO11'),
('Dommo ON','DMMO3'),
('Dommo ON Termo','DMMO3T'),
('Dtcom BDR','DTCY3'),
('Dte Energy','D1TE34'),
('Duke Energy BDR','DUKB34'),
('DuPont Nemours','DDNB34'),
('Duratex ON','DTEX3'),
('Ebay BDR','EBAY34'),
('Ecolab','E1CL34'),
('Ecorodovias ON','ECOR3'),
('EDP Brasil ON','ENBR3'),
('Electro Aco Altona','EALT3'),
('Electro Aco Altona PN','EALT4'),
('Elekeiroz ON','ELEK3'),
('Elekeiroz PN','ELEK4'),
('Elektro PN','EKTR4'),
('Eletric Servicos','EKTR3'),
('Eletricas Para CELPA Pref B','EQPA6'),
('Eletrobras Eletropar','LIPR3'),
('Eletrobras ON','ELET3'),
('Eletrobras PNB','ELET6'),
('Eletropaulo ON','ELPL3'),
('Eli Lilly BDR','LILY34'),
('EMAE PN','EMAE4'),
('Embraer ON','EMBR3'),
('Enauta ON','ENAT3'),
('Encorpar','ECPR3'),
('Energ De Brasilia A Pref','CEBR5'),
('Energ De Brasilia B Pref','CEBR6'),
('Energisa Mato Grosso','ENMT4'),
('Energisa MT ON','ENMT3'),
('Energisa ON','ENGI3'),
('Energisa PN','ENGI4'),
('Energisa Unit','ENGI11'),
('Eneva ON','ENEV3'),
('Engie Brasil ON','EGIE3'),
('Equatorial ON','EQTL3'),
('Equatorial Para Distribuidora de Energia SA','EQPA3'),
('Equatorial Para Distribuidora Enrg','EQPA7'),
('Estadual Geracao Transmissao','EEEL4'),
('Eternit ON','ETER3'),
('Eucatex','EUCA3'),
('Eucatex PN','EUCA4'),
('Europa 105','ERPA11'),
('Even ON','EVEN3'),
('Even Permuta Kinea','KINP11'),
('Evergy','E1VR34'),
('Eversource','E1SE34'),
('Excelsior Alimentos PN','BAUH4'),
('Exxon Mobil BDR','EXXO34'),
('Eztec ON','EZTC3'),
('Facebook BDR','FBOK34'),
('Fedex BDR','FDXB34'),
('Fer Heringer ON','FHER3'),
('Ferbasa ON','FESA3'),
('Ferbasa PN','FESA4'),
('Ferrovia Centro Atlantica ON','VSPT3'),
('FI Imobiliario Votorantim Logistica','VTLT11'),
('FI Imobiliario Votorantim Shopping','VSHO11'),
('FII A Branca','FPAB11'),
('FII Abc Imob','ABCP11'),
('FII Absoluto','BPFF11'),
('FII Aesapar','RBED11'),
('FII Alianza','ALZR11'),
('FII Anh Educ','FAED11'),
('FII Atrium Shopping Santo Andre','ATSA11'),
('FII Banrisul','BNFS11'),
('FII BB Corp','BBRC11'),
('FII BB Prgii','BBPO11'),
('FII BB R Pap','RNDP11'),
('FII Bc FFII Ci','BCFF11'),
('FII Bc Fund','BRCR11'),
('FII Bcia','BCIA11'),
('FII Bees Cri','BCRI11'),
('FII BM Thera','THRA11'),
('Fii Bre Vic','BREV11'),
('FII BRLPROP','BPRP11'),
('FII BTG PACTUAL CREDITO IMOBILIARIO','BTCR11'),
('FII C Branco','CBOP11'),
('FII C Jardim','BBVJ11'),
('FII C Textil','CTXT11'),
('FII Campusfl','FCFL11'),
('Fii Cenesp','CNES11'),
('FII Ceo Ccp','CEOC11'),
('FII Crianca','HCRI11'),
('FII CSHG Cri','HGCR11'),
('FII CSHG Log','HGLG11'),
('FII CSHG Urb','HGRU11'),
('FII Cshgjhsf','HGPO11'),
('FII Cshgshopci Er','HGBS11'),
('FII Cx Rbrav','CXRI11'),
('FII Cx Trx','CXTL11'),
('FII D Pedro','PQDP11'),
('FII Dea Care','CARE11'),
('FII Domo','DOMC11'),
('FII Europar','EURO11'),
('FII Excellence','FEXC11'),
('FII Fator Ve','VRTA11'),
('FII Floripa','FLRP11'),
('FII Galeria','EDGA11'),
('FII Gen Shop','FIGS11'),
('FII Ggr Covepi','GGRC11'),
('FII Green Towers','GTWR11'),
('FII HABIT II','HABT11'),
('FII Hedmoca','HMOC11'),
('FII HG Real','HGRE11'),
('FII Higienop','SHPH11'),
('FII Hotel Mx','HTMX11'),
('Fii Housi','HOSI11'),
('FII Htopfof2','FOFT11'),
('FII Htopfof3','HFOF11'),
('FII Indl Br','FIIB11'),
('FII Jhsf Fbv','RBBV11'),
('FII Js Real','JSRE11'),
('FII Kii Real','KNRE11'),
('FII Kinea','KNRI11'),
('FII Kinea Hy','KNHY11'),
('FII Kinea Ri','KNCR11'),
('FII Lourdes','NSLU11'),
('FII Louveira','GRLV11'),
('Fii Maua Capital','MCCI11'),
('FII Max Ret','MAXR11'),
('FII Maxi Ren','MXRF11'),
('FII Memorial','FMOF11'),
('FII Merc Br','MBRF11'),
('FII Merito','MFII11'),
('FII Mogno','MGFF11'),
('FII Olimpia','VLOL11'),
('FII Ouri Jpp','OUJP11'),
('FII Ouricyre','OUCY11'),
('FII P Vargas','PRSV11'),
('FII Panamby','PABY11'),
('FII Polo Cri','PORD11'),
('FII Polo I','PLRI11'),
('Fii Rb Capital I','RFOF11'),
('FII Rb Gsb I','RBGS11'),
('FII Rb II','RBRD11'),
('FII Rbralpha','RBRF11'),
('FII Rbresid2','RBDS11'),
('FII Rbrhgrad','RBRR11'),
('FII Rio Bravo Renda Corporativa','RCRB11'),
('FII Rio Bravo Rendo Varejo','RBVA11'),
('FII Riobcri2','RBVO11'),
('FII Riobrcib','RBCB11'),
('FII Rionegro','RNGO11'),
('FII S F Lima','FLMA11'),
('FII Sant Age','SAAG11'),
('Fii Sant Ren','SARE11'),
('FII Scp','SCPF11'),
('FII Sdi Log','SDIL11'),
('FII Shopjsul','JRDM11'),
('FII Sp Downt','SPTW11'),
('FII Tboffice','TBOF11'),
('FII Tg Ativo','TGAR11'),
('FII The One','ONEF11'),
('FII Torre Al','ALMI11'),
('FII Torre No','TRNT11'),
('Fii Trx Real','TRXF11'),
('FII Trxe Cor','XTED11'),
('FII UBS (BR) OFFICE','RECT11'),
('FII V Parque','FVPQ11'),
('FII Vbi 4440','FVBI11'),
('Fii Vbi Reit','RVBI11'),
('FII Vidanova','FIVN11'),
('FII Vinci Sc','VISC11'),
('FII XP Indl','XPIN11'),
('FII XP Macae','XPCM11'),
('Finam CI','FNAM11'),
('Financeira Alfa ON','CRIV3'),
('Financeira Alfa PN','CRIV4'),
('Finor','FNOR11'),
('FIP Infra Estr BB Votorantim II A','ESUD11'),
('FIP Infra Estr BB Votorantim III A','ESUT11'),
('Fip Perfin','PFIN11'),
('FIP XP Omega I','XPOM11'),
('First Solar BDR','FSLR34'),
('Fiset FL Ref CI','FSRF11'),
('FISET FL REF PRF','FSPE11'),
('Fiset Tur CI','FSTU11'),
('Fleury ON','FLRY3'),
('Fomento Economico Mexicano BDR','FMXB34'),
('Ford Motor BDR','FDMO34'),
('Fras-Le ON','FRAS3'),
('Freeport Mcmoranpper Gold BDR','FCXO34'),
('Fundo Inves','WPLZ11'),
('Gaec Educacao ON Termo','ANIM3T'),
('Gafisa','GFSA1'),
('Gafisa ON','GFSA3'),
('Gap BDR','GPSI34'),
('General Dynamicsrp BDR','GDBR34'),
('General Electric BDR','GEOO34'),
('General Motors BDR','GMCO34'),
('General Severiano','HBTT11'),
('General Shopping ON','GSHP3'),
('Ger Paranapanema PN','GEPA4'),
('Gerdau ON','GGBR3'),
('Gerdau PN','GGBR4'),
('Gilead Sciences BDR','GILD34'),
('Gol PN','GOLL4'),
('Goldmanchs Group BDR','GSGI34'),
('GoPro BDR','GPRO34'),
('GP Invest BDR A','GPIV33'),
('GPC Part ON','GPCP3'),
('Grazziotin ON','CGRA3'),
('Grazziotin PN','CGRA4'),
('Grendene ON','GRND3'),
('Grupo RCFA','RCFA11'),
('Grupo SBF Centauro','CNTO3'),
('Guararapes ON','GUAR3'),
('Habitasul PN','HBTS5'),
('Haga Industria Comercio','HAGA3'),
('Haga PN','HAGA4'),
('Halliburton BDR','HALI34'),
('Hapvida ON','HAPV3'),
('HAZ','ATCR11'),
('Hectare Ce Fdo Inv Imob','HCTR11'),
('Hedge Logistica','HLOG11'),
('Hedge Realty','HRDF11'),
('Hedge Shopping','HPDP11'),
('Hedge Top FOFII','TFOF11'),
('Helbor ON','HBOR3'),
('Hercules PN','HETA4'),
('Hermes Pardini ON','PARD3'),
('Hershey BDR','HSHY34'),
('Hewlett Packard BDR','HPQB34'),
('Home Depot BDR','HOME34'),
('Honeywell BDR','HONB34'),
('Hospital Unimed Sul Capixaba','HUSC11'),
('Hoteis Othon PN','HOOT4'),
('HSI Malls FII','HSML11'),
('Husi Fundo','HUSI11'),
('Hypera ON','HYPE3'),
('IBM BDR','IBMB34'),
('Ideiasnet ON','IDNT3'),
('IGB ON','IGBR3'),
('Iguatemi ON','IGTA3'),
('Ihs Markit','I1NF34'),
('IMC ON','MEAL3'),
('Inds Romi ON','ROMI3'),
('Industrias JB Duarte Right 1','JBDU1'),
('Industrias JB Duarte Right 2','JBDU2'),
('Indusval ON','IDVL3'),
('Indusval PN','IDVL4'),
('Inepar ON','INEP3'),
('Inepar PN','INEP4'),
('Infra Real State','FINF11'),
('Integral Brei Reit','IBFF11'),
('Intel BDR','ITLC34'),
('Inter Titulos','BICR11'),
('Intermedica ON','GNDI3'),
('International Flavors','I1FF34'),
('Iochpe-Maxion ON','MYPK3'),
('IRB Brasil ON','IRBR3'),
('Iridium Recebíveis Imob','IRDM11'),
('Itau Unibanco ON','ITUB3'),
('Itau Unibanco PN','ITUB4'),
('Itausa ON','ITSA3'),
('Itausa PN','ITSA4'),
('Itautec','ITEC3'),
('J B Duarte ON','JBDU3'),
('J B Duarte PN','JBDU4'),
('J C Penney BDR','JCPC34'),
('JBS ON','JBSS3'),
('Jefferies Fin','J1EF34'),
('Jereissati Part ON','JPSA3'),
('JHSF Part ON','JHSF3'),
('Joao Fortes ON','JFEN3'),
('Johnson Johnson BDR','JNJB34'),
('Josapar ON','JOPA3'),
('Josapar PN','JOPA4'),
('JP Morgan Chase BDR','JPMC34'),
('Jpp Allocation','JPPA11'),
('JPP Capital','JPPC11'),
('JSL ON','JSLG3'),
('Karsten','CTKA3'),
('Karsten PN','CTKA4'),
('Kellogg','K1EL34'),
('Kepler Weber','KEPL11'),
('Kepler Weber ON','KEPL3'),
('Kimberly Clarkrp BDR','KMBB34'),
('Kinea Índice de Preços FDO INV IMOB - FII','KNIP11'),
('Klabin ON','KLBN3'),
('Klabin PN','KLBN4'),
('Klabin Unit','KLBN11'),
('Kraft Heinz BDR','KHCB34'),
('L Brands BDR','LBRN34'),
('Lam Res','L1RC34'),
('Le Lis Blanc ON','LLIS3'),
('Lifemed','LMED3'),
('Light ON','LIGT3'),
('Linde','L1IN34'),
('Linx ON','LINX3'),
('Liq ON','ATMP3'),
('Lkq','L1KQ34'),
('Localiza ON','RENT3'),
('Locamerica ON','LCAM3'),
('Locaweb On','LWSA3'),
('Lockheed Martin BDR','LMTB34'),
('Log CP ON','LOGG3'),
('Log-in Logistica Right','LOGN12'),
('Log-In ON','LOGN3'),
('Logcp Inter Fundo','LGCP11'),
('Lojas Americanas ON','LAME3'),
('Lojas Americanas PN','LAME4'),
('Lojas Marisa ON','AMAR3'),
('Lojas Renner ON','LREN3'),
('Lopes Brasil ON','LPSB3'),
('Luggo Fundo','LUGG11'),
('Lululemon','L1UL34'),
('Lupatech ON','LUPA3'),
('M.Dias Branco ON','MDIA3'),
('MAC Fundo de Investimento Imobiliario','DMAC11'),
('Macy’s BDR','MACY34'),
('Magazine Luiza ON','MGLU3'),
('Mangels PN','MGEL4'),
('Marcopolo ON','POMO3'),
('Marcopolo PN','POMO4'),
('Marcopolo PRF','POMO10'),
('Marfrig ON','MRFG3'),
('Marriott','M1TT34'),
('Mastercard BDR','MSCD34'),
('Mccormick','M1KC34'),
('McDonalds BDR','MCDC34'),
('Mecanicas','BDLL3'),
('Medtronic BDR','MDTC34'),
('Melhor Pref ','MSPA4'),
('Mendes Junior','MEND6'),
('Mendes Junior PNA','MEND5'),
('Mercadolibre BDR','MELI34'),
('Mercantil Brasil Financeira','MERC4'),
('Merck BDR','MRCK34'),
('Met. Gerdau ON','GOAU3'),
('Met. Gerdau PN','GOAU4'),
('Metal Iguacu PN','MTIG4'),
('Metal Leve ON','LEVE3'),
('Metalfrio ON','FRIO3'),
('Metalurgica Riosulense','RSUL4'),
('Metisa PN','MTSA4'),
('Metisa Metalg Tim','MTSA3'),
('Metlife BDR','METB34'),
('Microsoftrp BDR','MSFT34'),
('Mills ON','MILS3'),
('Minerva','BEEF11'),
('Minerva ON','BEEF3'),
('Minupar Part ON','MNPR3'),
('Mitre Realty On','MTRE3'),
('MMX ON','MMXM3'),
('MMX TPR','MMXM11'),
('Mondelez International BDR','MDLZ34'),
('Monster Beverage','M1NS34'),
('Monteiro Aranha','MOAR3'),
('Morgan Stanley Bank BDR','MSBR34'),
('Mosaic Company BDR','MOSC34'),
('Moura Dubeux On','MDNE3'),
('Movida ON','MOVI3'),
('MRV ON','MRVE3'),
('Multi Properties','PRTS11'),
('Multi Shoppings','SHOP11'),
('Multiplan ON','MULT3'),
('Mundial ON','MNDL3'),
('Nadir Figueiredo','NAFG3'),
('National Oilwell','N1OV34'),
('Natura ON','NTCO3'),
('NCH Brasil Recebíveis Imobiliários','NCHB11'),
('Neoenergia ON','NEOE3'),
('Nestpar','NPAR11'),
('Netflix BDR','NFLX34'),
('Newport Logistica','NEWL11'),
('Newport Renda Urbana','NEWU11'),
('News','N1WS34'),
('Nike BDR','NIKE34'),
('Nordon Metalg','NORD3'),
('Norte Cosern A Pref','CSRN5'),
('Norte Cosern B Pref','CSRN6'),
('Novo Horizonte','NVHO11'),
('Nutriplant ON','NUTR3'),
('Odontoprev ON','ODPV3'),
('Oi ON','OIBR3'),
('Oi PN','OIBR4'),
('Omega Ger ON','OMGE3'),
('Oracle BDR','ORCL34'),
('OSX Brasil ON','OSXB3'),
('Ouro Fino ON','OFSA3'),
('Ouro Preto Desenvolvimento Imobiliário I','ORPD11'),
('Panatlantica','PATI3'),
('Panatlantica PN','PATI4'),
('Paranapanema ON','PMAM3'),
('Patria Edifícios Corporativos FII','PATC11'),
('PDG Realt ON','PDGR3'),
('Pedra Negra Renda Imobiliária','FPNG11'),
('Pepsico BDR','PEPB34'),
('Petrobras Distr ON','BRDT3'),
('Petrobras ON','PETR3'),
('Petrobras PN','PETR4'),
('Petrorio ON','PRIO3'),
('Petróleo Manguinhos ON','RPMG3'),
('Pettenati PN','PTNT4'),
('Pfizer BDR','PFIZ34'),
('Pine PN','PINE4'),
('Pioneer Natural','P1IO34'),
('Plascar Part ON','PLAS3'),
('Plural Recebiveis','PLCR11'),
('Polo Shopping Indaiatuba','VPSI11'),
('Pomifrutas ON','FRTA3'),
('Porto Seguro ON','PSSA3'),
('Porto Sudeste','PSVM11'),
('Portobello ON','PTBL3'),
('Positivo Inf ON','POSI3'),
('PPLA Unit','PPLA11'),
('Priner Servicos Industriais SA','PRNR3'),
('Procter Gamble BDR','PGCO34'),
('Profarma ON','PFRM3'),
('Prologis Brazil Logistics Venture','PBLV11'),
('Prudential','P1DT34'),
('Pão de Açúcar CBD ON','PCAR3'),
('Qualcomm BDR','QCOM34'),
('Qualicorp ON','QUAL3'),
('Quasar Agro','QAGR11'),
('Raia Drogasil ON','RADL3'),
('Randon Part ON','RAPT3'),
('Randon Part PN','RAPT4'),
('Rb Cap','RBCO11'),
('Rb Cap','RSPD11'),
('Rb Capital','RBTS11'),
('RBR Private Crédito Imobiliário','RBRY11'),
('RBR Properties','RBRP11'),
('Recrusul ON','RCSL3'),
('Recrusul PN','RCSL4'),
('Rede Energia ON','REDE3'),
('Reit Recebiveis','ARRI11'),
('Renova ON','RNEW3'),
('Renova PN','RNEW4'),
('Renova Unit','RNEW11'),
('Republic Services','R1SG34'),
('Rio Bravo Credito','RBIV11'),
('Rio Bravo IFIX','RBFF11'),
('Rio Paranapanema Energia ON','GEPA3'),
('Rodobens ON','RDNI3'),
('Ross Stores BDR','ROST34'),
('Rossi Resid ON','RSID3'),
('Royal Caribbean','R1CL34'),
('Rumo ON','RAIL3'),
('S And P Global','SPGI34'),
('Sabesp ON','SBSP3'),
('Salesforce.com BDR','SSFO34'),
('Sanchez Energy BDR','SANC34'),
('Sanepar ON','SAPR3'),
('Sanepar PN','SAPR4'),
('Sanepar Unit','SAPR11'),
('Sansuy PNB','SNSY5'),
('Santander Brasil ON ','SANB3'),
('Santander Brasil PN ','SANB4'),
('Santander Brasil Unit','SANB11'),
('Santander Papeis Imobiliários CDI','SADI11'),
('Santanense ON','CTSA3'),
('Santanense PN','CTSA4'),
('Santos Brasil ON','STBP3'),
('Sao Carlos ON','SCAR3'),
('Sao Martinho ON','SMTO3'),
('Sao Paulo Turismo','AHEB3'),
('Saraiva ON','SLED3'),
('Saraiva PN','SLED4'),
('Saraiva PN','SLED2'),
('SC 401','FISC11'),
('Schlumberger BDR','SLBG34'),
('Schulz PN','SHUL4'),
('SDI Properties','SDIP11'),
('Seguros Alianca','CSAB3'),
('Seguros Alianca Pref','CSAB4'),
('Ser Educacional ON','SEER3'),
('Ser Educacional ON Termo','SEER3T'),
('Sinqia ON','SQIA3'),
('SLC Agricola ON','SLCE3'),
('Smiles ON','SMLS3'),
('Smiles PN','SMLS3T'),
('Socopa Fundo de Investimento Imobiliário','REIT11'),
('Somos Educacao ON ','SEDU3'),
('Sondotecnica PNA','SOND5'),
('Sondotecnica PNB','SOND6'),
('SPA Fundo de Investimento Imobiliário','SPAF11'),
('Springer A Pref','SPRI5'),
('Springer B Pref','SPRI6'),
('Springer ON','SPRI3'),
('Springs ON','SGPS3'),
('Sprint BDR','SPRN34'),
('Starbucks BDR','SBUB34'),
('STARX FII','STRX11'),
('Sul America','SULA4'),
('Sul America Pref','SULA3'),
('Sul America Unit','SULA11'),
('Suzano Papel ON','SUZB3'),
('São Domingos','FISD11'),
('São Fernando','SFND11'),
('Taesa ON','TAEE3'),
('Taesa PN','TAEE4'),
('Taesa Unit','TAEE11'),
('Take Two Interactive','T1TW34'),
('Target BDR','TGTB34'),
('Tarpon ON','TRPN3'),
('Taurus Armas Bônus de Subscrição B','TASA13'),
('Taurus Armas Bônus de Subscrição C','TASA15'),
('Taurus Armas Bônus de Subscrição D','TASA17'),
('Taurus Armas ON','TASA3'),
('Taurus Armas PN','TASA4'),
('Technipfmc','T1EC34'),
('Technos ON','TECN3'),
('Tecnisa ON','TCSA3'),
('Tecnosolo ON','TCNO3'),
('Tecnosolo PN','TCNO4'),
('Tectoy ON','TOYB3'),
('Tectoy PN','TOYB4'),
('Tegma ON','TGMA3'),
('Teka PN','TEKA4'),
('Teka Tecelagem','TEKA3'),
('Tekno Pref','TKNO4'),
('Telebras ON','TELB3'),
('Telebras PN','TELB4'),
('Telefonica Brasil ON','VIVT3'),
('Telefonica Brasil PN','VIVT4'),
('Tenda ON','TEND3'),
('Terra Santa ON','TESA3'),
('Tesla Motors BDR','TSLA34'),
('Texas Instruments BDR','TEXA34'),
('Textil Renauxview PN','TXRX4'),
('The Progressive','P1GR34'),
('Thermo Fisher Scientific','TMOS34'),
('Tiffany BDR','TIFF34'),
('TIM ON','TIMP3'),
('Time For Fun ON','SHOW3'),
('Tordesilhas EI','TORD11'),
('Totvs ON','TOTS3'),
('Tourmalet I','TORM13'),
('Tourmalet II','TOUR11'),
('Trane Tech','I1RP34'),
('Transdigm','T1DG34'),
('Transinc','TSNC11'),
('Transocean BDR','RIGG34'),
('Travelers Companies BDR','TRVC34'),
('Treecorp','TCPF11'),
('Trevisa Invest','LUXM4'),
('Trisul ON','TRIS3'),
('Triunfo ON','TPIS3'),
('Tupy ON','TUPY3'),
('Twitter BDR','TWTR34'),
('U.S. Bancorp BDR','USBC34'),
('UBS BDR','UBSG34'),
('Ultrapar ON','UGPA3'),
('Under Armour','U1AI34'),
('Unicasa ON','UCAS3'),
('Union Pacific BDR','UPAC34'),
('Unipar ON','UNIP3'),
('Unipar PNA','UNIP5'),
('Unipar PNB','UNIP6'),
('United Parcel Service BDR','UPSS34'),
('United States Steel BDR','USSX34'),
('United Technologiesrp BDR','UTEC34'),
('Usiminas ON','USIM3'),
('Usiminas PNA','USIM5'),
('Usiminas PNB','USIM6'),
('V2 Properties','VVPR11'),
('Vale ON','VALE3'),
('Valero Energy BDR','VLOE34'),
('Valid ON','VLID3'),
('Valora Cri Indice','VGIP11'),
('VALORA RE III FII','VGIR11'),
('Vbi Cri','CVBI11'),
('Vectis Juros','VCJR11'),
('Vector Queluz Lajes Corporativas','VLJS11'),
('Vereda','VERE11'),
('Verizon Communications BDR','VERZ34'),
('Via Varejo ON','VVAR3'),
('Vinci Energia','VIGT11'),
('VINCI LOGISTICA FII','VILG11'),
('Vinci Offices','VINO11'),
('Visa BDR','VISA34'),
('Vivara','VIVA3'),
('Viver ON','VIVR3'),
('Votorantim Securities Master','VOTS11'),
('Vulcabras ON','VULC3'),
('Wal Mart Stores BDR','WALM34'),
('Walt Disney BDR','DISB34'),
('Weg ON','WEGE3'),
('Wells Fargo BDR','WFCO34'),
('Western Union BDR','WUNI34'),
('Wetzel','MWET3'),
('Wetzel PN','MWET4'),
('Whirlpool ON','WHRL3'),
('Whirlpool PN','WHRL4'),
('Wilson Sons DR3','WSON33'),
('Wiz ON','WIZS3'),
('WLM Industria e Comercio ON','WLMM3'),
('WLM Industria e Comercio PN','WLMM4'),
('Ww Grainger','G1WW34'),
('Xerox BDR','XRXB34'),
('Xp Credito','XPCI11'),
('XP HOTEIS FDO INV IMOB','XPHT11'),
('XP HOTEIS FII','XPHT12'),
('Xp Infra','XPIE11'),
('XP Log FII','XPLG11'),
('Xp Prop','XPPR11'),
('Xp Selection','XPSF11'),
('Yaguara Capital High Yield','YCHY11'),
('Yduqs Part ON','YDUQ3'),
('Zimmer Biomet','Z1BH34'),
('Áquilla','AQLL11')
;
-- 
-- INSERT INTO ativo (codigo, nome, tipo)
-- VALUES 
-- ('ABEV3','AMBEV','ON'),
-- ('AZUL4','AZUL','PN N2'),
-- ('B3SA3','B3','ON NM'),
-- ('BBAS3','BANCO DO BRASIL','ON NM'),
-- ('BBDC3','BRADESCO','ON EB N1'),
-- ('BBDC4','BRADESCO','PN EB N1'),
-- ('BBSE3','BB SEGURIDADE','ON NM'),
-- ('BPAC11','BTG PACTUAL','UNT N2'),
-- ('BRAP4','BRADESPAR','PN N1'),
-- ('BRDT3','PETROBRAS DISTR','ON NM'),
-- ('BRFS3','BRF','ON NM'),
-- ('BRKM5','BRASKEM','PNA N1'),
-- ('BRML3','BR MALLS PAR','ON NM'),
-- ('BTOW3','B2W DIGITAL','ON NM'),
-- ('CCRO3','CCR','ON ED NM'),
-- ('CIEL3','CIELO','ON NM'),
-- ('CMIG4','CEMIG','PN N1'),
-- ('COGN3','COGNA EDUCACAO','ON NM'),
-- ('CRFB3','CARREFOUR','ON NM'),
-- ('CSAN3','COSAN','ON NM'),
-- ('CSNA3','CSN','ON'),
-- ('CVCB3','CVC BRASIL','ON NM'),
-- ('CYRE3','CYRELA REALT','ON NM'),
-- ('ECOR3','ECORODOVIAS','ON NM'),
-- ('EGIE3','ENGIE BRASIL','ON NM'),
-- ('ELET3','ELETROBRAS','ON N1'),
-- ('ELET6','ELETROBRAS','PNB N1'),
-- ('EMBR3','EMBRAER','ON NM'),
-- ('ENBR3','EDP BRASIL','ON NM'),
-- ('EQTL3','EQUATORIAL','ON NM'),
-- ('FLRY3','FLEURY','ON NM'),
-- ('GGBR4','GERDAU','PN N1'),
-- ('GNDI3','INTERMEDICA','ON NM'),
-- ('GOAU4','MET. GERDAU','PN N1'),
-- ('GOLL4','GOL','PN N2'),
-- ('HAPV3','HAPVIDA','ON NM'),
-- ('HGTX3','CIA HERING','ON NM'),
-- ('HYPE3','HYPERA','ON NM'),
-- ('IGTA3','IGUATEMI','ON NM'),
-- ('IRBR3','IRB BRASIL','ON NM'),
-- ('ITSA4','ITAUSA','PN N1'),
-- ('ITUB4','ITAU UNIBANCO','PN N1'),
-- ('JBSS3','JBS','ON NM'),
-- ('KLBN11','KLABIN','UNT N2'),
-- ('LAME4','LOJAS AMERICANAS','PN N1'),
-- ('LREN3','LOJAS RENNER','ON NM'),
-- ('MGLU3','MAGAZINE LUIZA','ON NM'),
-- ('MRFG3','MARFRIG','ON NM'),
-- ('MRVE3','MRV','ON NM'),
-- ('MULT3','MULTIPLAN','ON N2'),
-- ('NTCO3','NATURA','ON NM'),
-- ('PCAR3','PÃO DE AÇUCAR CBD','ON NM'),
-- ('PETR3','PETROBRAS','ON N2'),
-- ('PETR4','PETROBRAS','PN N2'),
-- ('QUAL3','QUALICORP','ON NM'),
-- ('RADL3','RAIA DROGASIL','ON ED NM'),
-- ('RAIL3','RUMO','ON NM'),
-- ('RENT3','LOCALIZA','ON NM'),
-- ('SANB11','SANTANDER BRASIL','UNT'),
-- ('SBSP3','SABESP','ON NM'),
-- ('SMLS3','SMILES','ON NM'),
-- ('SULA11','SUL AMERICA','UNT N2'),
-- ('SUZB3','SUZANO PAPEL','ON NM'),
-- ('TAEE11','TAESA','UNT N2'),
-- ('TIMP3','TIM','ON NM'),
-- ('TOTS3','TOTVS','ON NM'),
-- ('UGPA3','ULTRAPAR','ON NM'),
-- ('USIM5','USIMINAS','PNA N1'),
-- ('VALE3','VALE','ON NM'),
-- ('VIVT4','TELEFONICA BRASIL','PN'),
-- ('VVAR3','VIA VAREJO','ON NM'),
-- ('WEGE3','WEG','ON NM'),
-- ('YDUQ3','YDUQS PART','ON NM');

  

INSERT INTO vendas (ativo_id, indicacao, preco_pago, preco_venda, rendimento, quantidade, total_investido, total_final, diferenca, aquisicao, venda) 
VALUES 
((SELECT id FROM ativo WHERE codigo = 'PETR4'),'Própria',15.86,16.75,5.61,100.00, 1586.00, 1675.00, 89.00,'2020-04-17','2020-04-24'),
((SELECT id FROM ativo WHERE codigo = 'ODPV3'),'Própria',13.92,15.15,8.84,100.00, 1392.00, 1515.00, 123.00,'2020-04-09','2020-04-22'),
((SELECT id FROM ativo WHERE codigo = 'RENT3'),'Própria',30.05,34.6,15.14,50.00, 1502.50, 1730.00, 227.50,'2020-04-14','2020-04-20'),
((SELECT id FROM ativo WHERE codigo = 'COGN3'),'Própria',4.98,5.48,10.04,100.00, 498.00, 548.00, 50.00,'2020-04-14','2020-04-15'),
((SELECT id FROM ativo WHERE codigo = 'XPCM11'),'Própria',46.45,50.35,8.40,100.00, 4645.00, 5035.00, 390.00,'2020-03-12','2020-04-15'),
((SELECT id FROM ativo WHERE codigo = 'ECOR3'),'Própria',9.98,11.01,10.32,100.00, 998.00, 1101.00, 103.00,'2020-04-08','2020-04-09'),
((SELECT id FROM ativo WHERE codigo = 'DTEX3'),'Própria',8.74,9.1,4.12,30.00, 262.20, 273.00, 10.80,'2020-04-07','2020-04-08'),
((SELECT id FROM ativo WHERE codigo = 'VVAR3'),'Própria',4.6,4.8,4.35,57.00, 262.20, 273.60, 11.40,'2020-04-07','2020-04-08'),
((SELECT id FROM ativo WHERE codigo = 'BBFI11B'),'Própria',2258,2315,2.52,2.00, 4516.00, 4630.00, 114.00,'2020-03-12','2020-04-08'),
((SELECT id FROM ativo WHERE codigo = 'RENT3'),'Própria',29.1,30.74,5.64,10.00, 291.00, 307.40, 16.40,'2020-04-07','2020-04-08'),
((SELECT id FROM ativo WHERE codigo = 'VVAR3'),'Clear',13.43,15.29,13.85,100.00, 1343.00, 1529.00, 186.00,'2020-01-15','2020-02-06'),
((SELECT id FROM ativo WHERE codigo = 'NTCO3'),'Própria',46.28,49.2,6.31,100.00,4628.00,4920.00,292.00,'2020-01-21','2020-01-14'),
((SELECT id FROM ativo WHERE codigo = 'EZTC3'),'Própria',53.74,58.34,8.56,50.00,2687.00,2917.00,230.00, '2020-01-07','2020-01-15')
;
            
            
